### ISSUE TITLE
Code is not up to date

### ISSUE THREAD

**Issue by azure517** [isac322/OneDrive-API-java#11]
I see many missing methods. 

Error:(268, 37) java: cannot find symbol
  symbol:   method getCode()
  location: variable response of type org.onedrive.network.sync.SyncResponse
Error:(269, 77) java: cannot find symbol
  symbol:   method getContent()
  location: variable response of type org.onedrive.network.sync.SyncResponse
Error:(272, 85) java: cannot find symbol
  symbol:   method getContent()
  location: variable response of type org.onedrive.network.sync.SyncResponse

**Comment by isac322** [comment]
First, thank you for attention.

But those are auto generated methods by [Lombok](https://projectlombok.org/).

Did you use [gradle](https://gradle.org/)?
`gradle jar` will make jar file in `./build/libs`.
